site_name: Accelerated Ray and Path Tracing
theme:
  name: material
plugins:
  - mkdocstrings:
     handlers:
        python:
            options:
                docstring_options:
                    ignore_init_summary: false
                    merge_init_into_class: true
  - search

nav:
  - Home: index.md
  - Models:
      - Sphere: models/sphere.md
