site_name: Accelerated Ray and Path Tracing
theme:
  name: material
plugins:
  - mkdocstrings:
     handlers:
        python:
            options:
                docstring_options:
                    ignore_init_summary: false
                    merge_init_into_class: true
  - search

nav:
  - Home: index.md
  - Models:
      - Triangle: models/triangle.md
      - Mesh: models/mesh.md
  - Core:
      - Ray: core/ray.md
      - Scene: core/scene.md
      - Utils: core/utils.md
      - Camera: core/camera.md
      - BVH: core/BVH.md
